#!/usr/bin/ruby

chiper = "ISS NVVK DIPXYWA PIT AVSUY QIAOP PWZEHVNWIEDZ. CDYT ZVM LOTK HDY AVSMHOVT HV HDOA HYFH, ZVM COSS QY IQSY HV NYH HDY ITACYW, CDOPD OA IKMGQWIHY."

print chiper.tr('ABCDEFGHIJKLMNOPQRSTUVWXYZ','SBWHPSMTAJDFUGICBRLNVORKEY')
