#!/usr/bin/ruby

print '
mQmPtphqGrboHhmgaqVhCdwTwignlQvjIopDqVpgaNrwkAzVcn
kHyNiPdSmgJmgrPiMjpnjdbuPucHnouwfKuPcybromnmbvfxJq
RnnOvWsceZeYzRyqnkaaFsffjenxoIhqHnIzorlOdwZoxYmAuN
wNnRppguwidvbtOqdbUngpZdbGqwYjfpLzPjRtwVwEqBbYmCqb
KwuziCoEwPsIkJgruTbhdyWpvPztAodufjZxLaZcUeFaklSmeR
folohVbXoDfIqMqgIrQhzedqZlFwaBndQkQexBdLsCfXebrEfi
OnSgYquyaqohxoDmLdDhwoOpgtkuRzeYziuvnuvnUuOtqasZue
YpKfAkmKcJcWeocQvJguVsZfVovgrztAiryZivHqyMjoLyJdkl
KifmoWeOjVnogiiaBzDfrsWlOeAzPxltamqQiujZrpZrUcIlyk
tdJbhmNpDbltOlLnAqVhcxgObghpdcScgIiayqygUgwatiEzgz
TsZgApUbbPynLfbzehzWsxcPbdcdfMucsCzjkWvjhMkiWuHfqu
qrcKwedqghiyHyMkSayRegeJcGw'.gsub(/[A-Z]|\n/,'').length
